export const shellColorConfig = {
  colorMap: {
    black: "#14151a",
    blue: "#BD93F9",
    cyan: "#8BE9FD",
    green: "#50FA7B",
    purple: "#FF79C6",
    red: "#FF5555",
    white: "#F8F8F2",
    yellow: "#F1FA8C",
    brightBlack: "#6272A4",
    brightBlue: "#D6ACFF",
    brightCyan: "#A4FFFF",
    brightGreen: "#69FF94",
    brightPurple: "#FF92DF",
    brightRed: "#FF6E6E",
    brightWhite: "#FFFFFF",
    brightYellow: "#FFFFA5",
  },
  defaultBackgroundColor: "black" as const,
  defaultForegroundColor: "white" as const,
  snippetTag: "p",
};
